// <auto-generated />
namespace PinePawRetreat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class explicitFKsandlazyloadingadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(explicitFKsandlazyloadingadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202601071544207_explicit FKs and lazy loading added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
