// <auto-generated />
namespace PinePawRetreat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class vaccinationverifiedStatusadd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vaccinationverifiedStatusadd));
        
        string IMigrationMetadata.Id
        {
            get { return "202604221349562_vaccination verifiedStatus add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
